#!/usr/bin/env expect  

set host localhost 
set port 22
set user roxma
set password 84839829

# log_user 0

spawn ssh $user@$host -p$port
set password_sended 0
expect {
	"*yes/no" { send "yes\r" }
	"*password" {
		send "$password\r" ;
		set password_sended 1
	}
}

if {$password_sended==0} {
	expect {
		"*password" {
			send "$password\r" ;
			set password_sended 1
		}
	}
}


send "exit\r"

# expect eof

