
FOO_ENV_BACK:=$(FOO_ENV)

# This can override the environment variable
FOO_ENV:=foo_env

# This cannot override variable passed from command line
FOO_CMD:=foo_cmd

all:
	echo $(FOO_ENV_BACK)
	echo $(FOO_CMD)
	echo $(FOO_ENV)

