
set nocompatible        	" Use Vim defaults (much better!)
syntax on
filetype plugin on

" encoding
set encoding=utf-8 fileencodings=ucs-bom,utf-8,gbk,gb18030,latin1 termencoding=utf-8


""
" load vimrc files in the "'s:customvimrc_local_software_dir' . '/user_vimrc/'"
" directory
if exists("s:customvimrc_local_software_dir")
	let s:userVimrcFiels = glob(s:customvimrc_local_software_dir . "/user_vimrc/*.vimrc")
	let s:userVimrcFielsArr = split(s:userVimrcFiels)
	for s:f in s:userVimrcFielsArr
		execute "source " . s:f
	endfor
endif

let mapleader = " "


func! s:TweakPlugBegin(dir,...)
	let g:_tweak_plugins_dir = a:dir
endfunc

" register plugins for vim-tweak
func! g:TweakPlug(...)
	if exists('g:_tweak_plugins')!=1
		let g:_tweak_plugins = {}
	endif
	if len(a:000)>0
		let g:_tweak_plugins[a:000[0]] = a:000[1:]
	endif
	return g:_tweak_plugins
endfunc

func! g:TweakHasPlug(repo)
	if has_key(TweakPlug(),a:repo) == 0
		return 0
	endif
	if finddir(fnamemodify(repo,":t"),g:_tweak_plugins_dir) == ""
		return 0
	endif
	return 1
endfunc

func! s:TweakBootstrap()
	try
		call tweak#bootstrap()
	catch /\V\^Vim(call):E117: Unknown function: tweak#bootstrap\$/
		let l:dummp = 0
	endtry
endfunc

" You should execute :PlugInstall to install plugins when open vim for the
" first time

command -nargs=+ -bar  TweakPlugBegin  call plug#begin(<args>) | call s:TweakPlugBegin(<args>) | TweakPlug 'roxma/vim-tweak'
command -nargs=+ -bar  TweakPlug  call g:TweakPlug(<args>) | Plug <args>
command -bar  TweakPlugEnd  call plug#end() | call s:TweakBootstrap()


TweakPlugBegin s:customvimrc_vim_dir.'/plugged/'

" TweakPlug 'altercation/vim-colors-solarized'
" TweakPlug 'noahfrederick/vim-noctu'
" TweakPlug 'w0ng/vim-hybrid'
TweakPlug 'morhetz/gruvbox'
" TweakPlug 'flazz/vim-colorschemes'
" TweakPlug 'ryanoasis/vim-devicons'


TweakPlug 'simeji/winresizer'
TweakPlug 'bling/vim-airline'

" I use my own simple configuration, don't need this plugin anymore
" TweakPlug 'edkolev/tmuxline.vim'

" git
TweakPlug 'tpope/vim-fugitive'
TweakPlug 'junegunn/gv.vim'
TweakPlug 'gregsexton/gitv'
TweakPlug 'airblade/vim-gitgutter'

TweakPlug 'roxma/vim-encode'
TweakPlug 'godlygeek/tabular'
TweakPlug 'tpope/vim-surround'
" cool, but still have some confuzing issues, not what I want
" TweakPlug 'terryma/vim-multiple-cursors'
TweakPlug 'dhruvasagar/vim-table-mode'

TweakPlug 'Lokaltog/vim-easymotion'

" YouCompleteMe slow down vim's start time, replace it with SimpleAutoComplPop
" TweakPlug 'Valloric/YouCompleteMe'
TweakPlug 'scrooloose/syntastic'
TweakPlug 'roxma/SimpleAutoComplPop'

TweakPlug 'majutsushi/tagbar'
TweakPlug 'scrooloose/nerdtree'
TweakPlug 'Xuyuanp/nerdtree-git-plugin'
" TweakPlug 'tiagofumo/vim-nerdtree-syntax-highlight'

" need to install the_silver_searcher first: https://github.com/ggreer/the_silver_searcher
TweakPlug 'rking/ag.vim'
" Replace ctrlp with fzf
" TweakPlug 'ctrlpvim/ctrlp.vim'
TweakPlug 'junegunn/fzf', { 'do': './install --no-key-bindings --no-completion --no-update-rc' } " only install fzf for vim
TweakPlug 'junegunn/fzf.vim'
" for the enhanced <Leader>* key
TweakPlug 'haya14busa/vim-asterisk'

" markdown
TweakPlug 'plasticboy/vim-markdown'

" php
" Use my own forked repo, I'm planning on performance improvment
TweakPlug 'roxma/phpcomplete.vim'

" vim go
TweakPlug 'fatih/vim-go'

" web front-end
TweakPlug 'jelera/vim-javascript-syntax'
" html
TweakPlug 'othree/html5.vim'
TweakPlug 'mattn/emmet-vim'


TweakPlug 'tmux-plugins/vim-tmux-focus-events'
TweakPlug 'roxma/vim-tmux-clipboard'

" crashes if no man page found
" TweakPlug 'jez/vim-superman'

" not needed
" TweakPlug 'christoomey/vim-tmux-navigator'

" Can't match JavaScript inside html <script> tag
" TweakPlug 'tmhedberg/matchit'

" Browse hacker news in vim
" TweakPlug 'ryanss/vim-hackernews'

TweakPlugEnd

