
set nocompatible        	" Use Vim defaults (much better!)
syntax on
filetype plugin on

" encoding
set encoding=utf-8 fileencodings=ucs-bom,utf-8,gbk,gb18030,latin1 termencoding=utf-8


""
" load vimrc files in the "'s:customvimrc_local_software_dir' . '/user_vimrc/'"
" directory
if exists("s:customvimrc_local_software_dir")
	let s:userVimrcFiels = glob(s:customvimrc_local_software_dir . "/user_vimrc/*.vimrc")
	let s:userVimrcFielsArr = split(s:userVimrcFiels)
	for s:f in s:userVimrcFielsArr
		execute "source " . s:f
	endfor
endif

let mapleader = " "

